In [1]:
from functions import *
import time
from datetime import datetime
import pandas as pd
import csv

* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation

In [3]:
# defining the parameters
ontology_path = "./ontologies/transportation.owl"
onto_path.append("./ontologies/")
#ontology_path = "./ontologies/TalentaBase.owl"
#starting_class = "Asset" # set to none to start at ontology root
starting_class = None
#obj_filename = "data/Infrastructure/Bridges/01/Old stone bridgeOBJ.obj"
image_size = 512 # size of rendered images in pixels
batch_size = 6 # number of pictures to take

# cars
obj_filename = "data/Jeep_Renegade_2016_obj/Jeep_Renegade_2016.obj"
#obj_filename = "data/subaru/_Subaru-Loyale.obj"
#obj_filename = "data/suv/car.obj"
#obj_filename = "data/sport/low_poly_car_obj.obj"
#obj_filename = "data/lowpolycar/CARMODEL.obj"

# helicopters
#obj_filename = "data/OH-58D/OH-58D.obj"
#obj_filename = "data/heli/raven.obj"
#obj_filename = "data/uh60/uh60.obj"
#obj_filename = "data/412/412.obj"
#obj_filename = "data/v22/v22.obj"

# planes
#obj_filename = "data/FA-18F/FA-18F.obj"
#obj_filename = "data/Su-34/Su-34.obj"
#obj_filename = "data/bf109/Bf109G.obj"
#obj_filename = "data/jet/plane.obj"
#obj_filename = "data/airbus/caravelle.obj"

# trains
#obj_filename = "data/electrictrain/electrictrain.obj"
#obj_filename = "data/old/train.obj"
#obj_filename = "data/tram/train.obj"
#obj_filename = "data/wap7/WAP7.obj"
#obj_filename = "data/lowpolytrain/lowpoly_train.obj"


# tracks
#obj_filename = "data/railway/Rotaia.obj"


# bridges
#obj_filename = "data/bridge/bridge.obj"
#obj_filename = "data/longbridge/bridge.obj"

file_type = '3D'
expected_class = 'Car'

In [ ]:
# get info about 3D model
vertices_count, faces_count = get3Dinfo(obj_filename)

# multiview-rendering
render_time_start = time.time()
images = batch_render(obj_filename, image_size, batch_size)
render_time_end = time.time()
render_time = render_time_end - render_time_start

# batch-prediction using ontology
CLIP_time_start = time.time()
predictions_class_list, predictions_value_list = predict_batch_ontology(images, ontology_path, starting_class=starting_class)
D = computeSums(predictions_class_list, predictions_value_list)
CLIP_time_end = time.time()
CLIP_time = CLIP_time_end - CLIP_time_start

print(D)
max_class = max(D, key=D.get)
print("It's a {}".format(max_class))

# instance creation
instance_name = createInstance(ontology_path, obj_filename, max_class)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch3d/io/mtl_io.py:102: UserWarning: Texture UV coordinates outside the range [0, 1].                 The integer part will be ignored to form a repeating pattern.
  warnings.warn(msg)

Center: [ 1.8826467e-08  8.8003266e-01 -1.6728052e-01]
Radius: 2.302417755126953
--------------------------
Bounding Sphere duration: 0.059612274169921875 seconds
--------------------------
We have 2384 vertices and 4734 faces.
--------------------------
Rendering Images duration: 7.465928792953491 seconds
--------------------------
--------------------------
Total Batch_: 7.525541067123413 seconds
--------------------------
-------------------
image index: 0
Car
0.9997960925102234
-------------------
-------------------
image index: 1
Car
0.9998424053192139
-------------------
-------------------
image index: 2
Car
0.999806821346283
-------------------
-------------------
image index: 3
Car
0.9993038177490234
-------------------

In [85]:
# read csv file
with open('runs.csv', 'a', newline='') as csvfile:
    # Create a CSV writer object
    csvwriter = csv.writer(csvfile)
    
    # Add a new row to the CSV file
    new_row = [datetime.now().strftime("%m/%d/%Y, %H:%M:%S"), obj_filename, file_type, vertices_count, faces_count,expected_class, batch_size, image_size, render_time, CLIP_time, render_time + CLIP_time, max_class, instance_name]

    csvwriter.writerow(new_row)

In [86]:
# read csv file
df = pd.read_csv('runs.csv')
df

,creation_date,filename,filetype,vertices_count,faces_count,class,batch_size,image_size,render_time,CLIP_time,total_time,predicted_class,instance_name
0,"04/26/2023, 16:54:34",data/Jeep_Renegade_2016_obj/Jeep_Renegade_2016...,3D,2384,4734,Car,3,512,4.161292,40.628072,44.789364,Car,Car_11
1,"04/26/2023, 16:55:59",data/subaru/_Subaru-Loyale.obj,3D,3393,5328,Car,3,512,4.526856,46.753546,51.280402,Car,Car_12
2,"04/26/2023, 16:57:19",data/suv/car.obj,3D,1082,2044,Car,3,512,1.726068,43.490771,45.216839,Car,Car_13
3,"04/26/2023, 16:58:30",data/sport/low_poly_car_obj.obj,3D,2800,5786,Car,3,512,4.430570,43.576268,48.006838,Car,Car_14
4,"04/26/2023, 16:59:56",data/lowpolycar/CARMODEL.obj,3D,2765,5456,Car,3,512,4.467727,43.595543,48.063270,Helicopter,Helicopter_0
5,"04/27/2023, 08:15:55",data/OH-58D/OH-58D.obj,3D,34938,66681,Helicopter,3,512,49.661977,39.585645,89.247622,Helicopter,Helicopter_1
6,"04/27/2023, 08:18:01",data/heli/raven.obj,3D,32683,56941,Helicopter,3,512,41.142968,40.126950,81.269918,Helicopter,Helicopter_2
7,"04/27/2023, 08:20:17",data/uh60/uh60.obj,3D,51663,86031,Helicopter,3,512,68.685484,37.611273,106.296757,Helicopter,Helicopter_3
8,"04/27/2023, 08:23:14",data/412/412.obj,3D,69070,118590,Helicopter,3,512,103.135210,37.708080,140.843290,Helicopter,Helicopter_4
9,"04/27/2023, 08:25:04",data/v22/v22.obj,3D,35489,60743,Helicopter,3,512,46.620212,39.326418,85.946630,Helicopter,Helicopter_5
10,"04/27/2023, 08:27:00",data/FA-18F/FA-18F.obj,3D,22529,42762,Plane,3,512,31.354017,39.934809,71.288826,Plane,Plane_0
11,"04/27/2023, 08:28:44",data/Su-34/Su-34.obj,3D,20860,39121,Plane,3,512,29.275458,38.359168,67.634626,Plane,Plane_1
12,"04/27/2023, 08:30:35",data/bf109/Bf109G.obj,3D,17293,32530,Plane,3,512,24.504903,37.968461,62.473364,Plane,Plane_2
13,"04/27/2023, 08:32:29",data/jet/plane.obj,3D,31595,60634,Plane,3,512,45.925126,39.493603,85.418729,Plane,Plane_3
14,"04/27/2023, 08:35:30",data/airbus/caravelle.obj,3D,81162,135775,Plane,3,512,98.894939,37.056779,135.951718,Plane,Plane_4
15,"04/27/2023, 08:36:50",data/electrictrain/electrictrain.obj,3D,5506,8340,Train,3,512,6.501069,38.140794,44.641863,Helicopter,Helicopter_6
16,"04/27/2023, 08:41:31",data/old/train.obj,3D,135841,266454,Train,3,512,206.766458,38.531895,245.298353,Train,Train_0
17,"04/27/2023, 08:44:17",data/tram/train.obj,3D,60418,117750,Train,3,512,90.828154,43.783525,134.611679,Train,Train_1
18,"04/27/2023, 08:53:03",data/wap7/WAP7.obj,3D,272217,543076,Train,3,512,462.139229,39.178949,501.318178,Train,Train_2
19,"04/27/2023, 08:54:01",data/lowpolytrain/lowpoly_train.obj,3D,1757,3001,Train,3,512,2.613718,39.329892,41.943610,Train,Train_3
20,"04/27/2023, 08:55:14",data/railway/Rotaia.obj,3D,512,768,Railroad,3,512,0.733021,25.760364,26.493385,Railroad,Railroad_0
21,"04/27/2023, 08:56:11",data/bridge/bridge.obj,3D,4178,5916,Bridge,3,512,4.670319,25.858220,30.528539,Bridge,Bridge_0
22,"04/27/2023, 09:09:35",data/longbridge/bridge.obj,3D,389012,778594,Bridge,3,512,655.477903,26.627361,682.105264,Bridge,Bridge_1
23,"04/27/2023, 14:12:38",data/electrictrain/electrictrain.obj,3D,5506,8340,Car,6,512,12.813027,85.031301,97.844328,Train,Train_4